### ISSUE TITLE
Document support for multiple sizes?

### ISSUE THREAD

**Issue by indolering** [haydenbleasel/favicons#30]
You thank some people in the readme for their input on multiple sizes.  Has this actually made it into the production system?  If so, could you document support for it?

**Comment by haydenbleasel** [comment]
Yeah sorry, it's a bit weird. Old implementation (1.x.x) of Favicons has support for multiple image sizes based on the icon size. New one has support for multiple image sizes based on the platform. I have to update this, thanks for pointing it out!

**Comment by indolering** [comment]
It is still not clear to me how I would, for example, specify a primary SVG for the larger sizes and a secondary image for 16x16 and 24x24.

**Comment by haydenbleasel** [comment]
That implementation of size-based images was in version 1. Since then, we've started using the RealFaviconGenerator API which gives us the ability to use platform-based images only, for example:

> A master picture can also be declared for each platform. For example, if a specific icon was designed for iOS:

```
"ios": {
	"master_picture": {
		"type": "url",
		"url": "http://somesite.com/some_pic.png"
	},
	"picture_aspect": "no_change"
},
```

With that in mind, if you'd like this functionality to be in the RealFaviconGenerator API then I recommend [contacting Philippe](http://realfavicongenerator.net/) as it's totally up to him :)

**Comment by troxler** [comment]
@haydenbleasel Has this changed in the meantime? The configuration example states that `source` can be an "array of `{ size: filepath }`". But how exactly would be the notation of that?
