### ISSUE TITLE
Follow HTML5 boilerplate

### ISSUE THREAD

**Issue by Stanzilla** [haydenbleasel/favicons#41]
They settled on using only one apple-touch-image because the majority of iOS devices are on 7+

Might be good to follow them

See https://github.com/h5bp/html5-boilerplate/commit/345925f04384b59929d8d39ba428cef548921408

**Comment by haydenbleasel** [comment]
Hey @Stanzilla, I definitely agree however there's 2 clauses:

1. Support for multiple Apple Touch Icons is not dropped and is in fact still recommended for quality icons i.e. not scaling a single icon to match a variety of resolutions.
2. The production of these icons and the metadata is done by RealFaviconGenerator (since this module is just a wrapper for the work I do there) so changing the API is a whole different story.

So for now, I think we'll stick with all the recommended icons until Apple tell us that it's no longer necessary (unlikely to be soon though). Thanks for the suggestion though, nice to be kept in the loop about the newest standards :+1:
