### ISSUE TITLE
when appending html it's replacing my single quotes 

### ISSUE THREAD

**Issue by jojoyuji** [haydenbleasel/favicons#42]
My single quotes are being replaced by `&apos;` :(

**Comment by gmhenderson** [comment]
+1

**Comment by gmhenderson** [comment]
Seems like this is an issue when Cheerio (and htmlparser2) [load()](https://github.com/cheeriojs/cheerio#loading)s the target html file. Not really a favicon-specific issue.

I ran into this when trying to inject meta tags into a twig template. My solution was to write the meta data into a blank html file, and then use Twig to include that in the `<head>`.

**Comment by haydenbleasel** [comment]
Sorry for the delay, I've had my uni exams. @gmhenderson is correct, it's HTMLParser's load function (specifically the option `decodeEntities`). I use another module to handle the HTML I/O in Favicons and I've updated that library and since Favicons requires the latest of every module, just do a new `npm install` and you should be good :+1:
